// Tokens used for Dependency Injection
export const ORGANIZATION_REPOSITORY = Symbol('ORGANIZATION_REPOSITORY');
export const TEAM_REPOSITORY = Symbol('TEAM_REPOSITORY');
export const USER_ORG_MEMBERSHIP_REPOSITORY = Symbol('USER_ORG_MEMBERSHIP_REPOSITORY');
export const USER_TEAM_MEMBERSHIP_REPOSITORY = Symbol('USER_TEAM_MEMBERSHIP_REPOSITORY');
export const ORG_INVITATION_REPOSITORY = Symbol('ORG_INVITATION_REPOSITORY');
export const ORG_USER_REPOSITORY = Symbol('ORG_USER_REPOSITORY');

export const ORGS_DB_CONNECTION_NAME = 'ORGS_DB_CONNECTION_NAME';
export const ORGS_CONFIG_TOKEN = 'ORGS_CONFIG_TOKEN';

export const USERS_GRPC_SERVICE = Symbol('USERS_GRPC_SERVICE');
