x-shared-network: &shared-network
  networks:
    - nmsvc-network
x-shared-postgres: &shared-postgres
  image: postgres:${POSTGRESQL_VERSION}
  environment:
    POSTGRES_USER: ${DB_ROOT_USER}
    POSTGRES_PASSWORD: ${DB_ROOT_PASSWORD}
    POSTGRES_DB: ${DB_NAME}

services:
  database-instance-1:
    <<: [*shared-postgres, *shared-network]
    container_name: nmsvc-database-instance-1
    ports:
      - ${DB_PORT_INSTANCE_1}:5432
    volumes:
      - database-instance-1-volume:/var/lib/postgresql/data

  database-instance-2:
    <<: [*shared-postgres, *shared-network]
    container_name: nmsvc-database-instance-2
    ports:
      - ${DB_PORT_INSTANCE_2}:5432
    volumes:
      - database-instance-2-volume:/var/lib/postgresql/data

  database-adminer:
    container_name: nmsvc-database-adminer
    image: dpage/pgadmin4
    depends_on:
      - database-instance-1
      - database-instance-2
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_ADMINER_USER}
      PGADMIN_DEFAULT_PASSWORD: ${DB_ADMINER_PASSWORD}
    ports:
      - ${DB_ADMINER_PORT}:80
    volumes:
      - database-adminer-volume:/var/lib/pgadmin
    <<: *shared-network

networks:
  nmsvc-network:
    driver: bridge
    name: nmsvc-network

volumes:
  database-instance-1-volume:
    name: nmsvc-database-instance-1-volume
  database-instance-2-volume:
    name: nmsvc-database-instance-2-volume
  database-adminer-volume:
    name: nmsvc-database-adminer-volume
